<?xml version="1.0"?>
  
  <!DOCTYPE memo [ 
  <!ELEMENT memo (to,from,title,message)>
  <!ELEMENT to	(#PCDATA) >
  <!ELEMENT from (#PCDATA) >
  <!ELEMENT title (#PCDATA) >
  <!ELEMENT message (#PCDATA) >
  ] >
  
  <memo>
    <to> Alan </to>
    <from> Alice </from>
    <title> Meetings </title>
    <message> Hi how are you... </message>
  </memo>
  